#FOR LOCAL TESTING
version: "3.8"

services:
  db:
    image: postgres:12.2-alpine
    container_name: "nectar-sql-db"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pgpassword
    volumes:
      - database_postgres:/var/lib/postgresql/data
  cache:
    image: redis:6.2-alpine
    container_name: "nectar-redis"
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - cache:/data

volumes:
  database_postgres:
  cache:
    driver: local