version: "3.8"

services:
  db:
    image: postgres:12.2-alpine
    container_name: "nectar-sql-db"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pgpassword
    networks:
      - fullstack
    volumes:
      - database_postgres:/var/lib/postgresql/data

  api:
    build: .
    container_name: "nectar-rest-api"
    environment:
      DB_USERNAME: "postgres"
      DB_PASSWORD: "pgpassword"
      DB_DB: "postgres"
      DB_HOST: "db"
      DB_PORT: "5432"
      SSL_MODE: "disable"
      TOKEN_SECRET: "nectar"
      FILE_SERVER_URL: "http://192.168.1.200:9000/assets/"
      ACCESS_KEY: "AKIA4QCYNL3ZG7TOS7OR"
      SECRET_KEY: "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"
      AWS_REGION: "us-east-2"
      AWS_ACL: "public-read"
      S3_BUCKET: "nectar-bucket-123"
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - fullstack

volumes:
  database_postgres:

networks:
  fullstack:
    driver: bridge


