version: "3.8"

services:
  db:
    image: postgres:12.2-alpine
    container_name: "nectar-sql-db"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pgpassword
    volumes:
      - database_postgres:/var/lib/postgresql/data

volumes:
  database_postgres: